language: java

jdk:
  - openjdk8

before_script:
  - echo "Build started"
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - echo "Build was failed"